# 当前工作流的名称
name: BLOG CI
# ci触发的条件
on:
  push: # 什么请求触发
    branches: 
    - blog # 作用在哪些分支上

jobs: # 构建的任务，一个工作流有多个构建任务，
  build-and-deploy:
    runs-on: ubuntu-latest # 在什么服务器上面执行这些任务，这里使用最新版本的ubuntu
    
    steps: # 构建任务的步骤，一个任务可分为多个步骤
    
    # 步骤1 拉取仓库代码
    - name: Checkout # 步骤名称
      uses: actions/checkout@v2
      with:
        submodules: true # Fetch Hugo themes (true OR recursive)
    # 步骤2 给当前服务器安装Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
#        extended: true
    # 步骤3 打包
    - name: build
      run: |
        hugo # 此处是构建脚本
      
    # 步骤6 部署项目
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        # 供用户访问的github access_token 下面的变量是在准备阶段自定义的变量
        access_token: ${{ secrets.BLOG_TOKEN }} 
        # 发布到指定分支
        branch: main
        # 指定发布的打包后的文件
        folder: ./public